### ISSUE TITLE
(plugin-utils): type: module not working

### ISSUE THREAD

**Issue by alexanderniebuhr** [windicss/vite-plugin-windicss#144]
there is still an issue with `type: module` in package.json, seems to be an type issue @antfu any idea?

```
⚠ ERROR: Invalid host defined options
⚠ ERROR: TypeError: Invalid host defined options
	at eval (eval at loadConfiguration (c:\Users\Alexander\.vscode-insiders\extensions\voorjaar.windicss-intellisense-0.11.5\out\extension.js:36061:27), <anonymous>:3:1)
	at loadConfiguration (c:\Users\Alexander\.vscode-insiders\extensions\voorjaar.windicss-intellisense-0.11.5\out\extension.js:36064:35)
```

**Comment by antfu** [comment]
Repro?

**Comment by alexanderniebuhr** [comment]
https://github.com/alexanderniebuhr/svelte-sveasy-windicss

**Comment by alexanderniebuhr** [comment]
@antfu update here, it works when running extension in debug `F5`, but does not work with published extension. So it might be an bundle issue in extension. You have any idea why it's different from running in debug `F5`

**Comment by alexanderniebuhr** [comment]
It is this build config.. can we change that to something newer than ES5, for VS Code Extension?
```
typescript({
    target: "es5",
    include: "src/**",
    outDir: outputDir,
    typescript: require("typescript"),
  })
```
