### ISSUE TITLE
Prebundling error: No matching export in "browser-external:path" for import "extname"

### ISSUE THREAD

**Issue by noook** [windicss/vite-plugin-windicss#189]
**Describe the bug**
When running the server for the first time, vite tries to prebundle dependencies, however it throws an error with Windicss:

```
> node_modules/@windicss/plugin-utils/dist/index.mjs:221:8: error: No matching export in "browser-external:path" for import "extname"
    221 │ import {extname} from "path";
        ╵         ~~~~~~~

error when starting dev server:
Error: Build failed with 1 error:
node_modules/@windicss/plugin-utils/dist/index.mjs:221:8: error: No matching export in "browser-external:path" for import "extname"
    at failureErrorWithLog (/Users/nook/repos/@golem-ai/docuchecker/vue/node_modules/esbuild/lib/main.js:1466:15)
    at /Users/nook/repos/@golem-ai/docuchecker/vue/node_modules/esbuild/lib/main.js:1148:28
    at runOnEndCallbacks (/Users/nook/repos/@golem-ai/docuchecker/vue/node_modules/esbuild/lib/main.js:938:63)
    at buildResponseToResult (/Users/nook/repos/@golem-ai/docuchecker/vue/node_modules/esbuild/lib/main.js:1146:7)
    at /Users/nook/repos/@golem-ai/docuchecker/vue/node_modules/esbuild/lib/main.js:1253:14
    at /Users/nook/repos/@golem-ai/docuchecker/vue/node_modules/esbuild/lib/main.js:629:9
    at handleIncomingPacket (/Users/nook/repos/@golem-ai/docuchecker/vue/node_modules/esbuild/lib/main.js:726:9)
    at Socket.readFromStdout (/Users/nook/repos/@golem-ai/docuchecker/vue/node_modules/esbuild/lib/main.js:596:7)
    at Socket.emit (node:events:365:28)
    at addChunk (node:internal/streams/readable:314:12)
```

**Minimal Reproductions**
**`package.json`**
```json
{
  "name": "xxxx",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "yarn generate-icons && vite",
    "build": "vite build",
    "test:unit": "# vue-cli-service test:unit",
    "lint": "# vue-cli-service lint",
    "dev": "vite",
    "generate-icons": "node ./src/assets/fonts/icons/generate-icons.js",
    "i18n:report": "# vue-cli-service i18n:report --src './src/**/*.?(js|vue)' --locales './src/locales/**/*.json'",
    "cypress": "cypress open"
  },
  "dependencies": {
    "@datadog/browser-rum": "^2.5.4",
    "axios": "^0.21.1",
    "js-file-download": "^0.4.11",
    "lodash": "^4.17.15",
    "v-tooltip": "^2.0.3",
    "vue": "^3.0.11",
    "vue-i18n": "^8.0.0",
    "vue-notification": "^1.3.20",
    "vue-router": "^4.0.8",
    "vuedraggable": "^2.24.3"
  },
  "devDependencies": {
    "@types/node": "^15.6.2",
    "@typescript-eslint/eslint-plugin": "^4.26.0",
    "@typescript-eslint/parser": "^4.26.0",
    "@vitejs/plugin-vue": "^1.2.3",
    "@vue/compiler-sfc": "^3.0.11",
    "@vue/test-utils": "^2.0.0-rc.6",
    "cypress": "^6.7.1",
    "dotenv": "^10.0.0",
    "eslint": "^7.27.0",
    "eslint-config-airbnb-base": "^14.2.1",
    "eslint-import-resolver-alias": "^1.1.2",
    "eslint-plugin-import": "^2.23.3",
    "eslint-plugin-vue": "^7.9.0",
    "jest-junit": "^12.0.0",
    "sass": "^1.34.0",
    "typescript": "^4.1.3",
    "vite": "^2.3.6",
    "vite-plugin-windicss": "^0.16.7",
    "windicss": "^3.0.12"
  }
}

```

**Versions**
- node: 14.15.0
- vite-plugin-windicss:^0.16.7
- vite:^2.3.6
- framework(vue/react/svelte/etc): Vue

**Additonal Context**

I can run the server by excluding the plugin in the optimize deps section of Vite config

**Comment by antfu** [comment]
Do you have `"esModuleInterop": true,` in your tsconfig.json?

**Comment by antfu** [comment]
Close due to inactive
