### ISSUE TITLE
[BUG] - Whenever I tried to edit the css file I got this error

### ISSUE THREAD

**Issue by sujit-baniya** [windicss/vite-plugin-windicss#278]
```
/web/node_modules/.pnpm/@windicss+plugin-utils@1.7.0/node_modules/@windicss/plugin-utils/dist/index.js:826
          attributesObject[name2].push(...value.split(regexClassSplitter).filter(Boolean));
                                                ^

TypeError: Cannot read property 'split' of undefined
    at /web/node_modules/.pnpm/@windicss+plugin-utils@1.7.0/node_modules/@windicss/plugin-utils/dist/index.js:826:49
    at Array.forEach (<anonymous>)
    at Object.buildPendingStyles (/web/node_modules/.pnpm/@windicss+plugin-utils@1.7.0/node_modules/@windicss/plugin-utils/dist/index.js:823:20)
    at getChangedModuleNames (/web/node_modules/.pnpm/vite-plugin-windicss@1.7.0_vite@2.8.0/node_modules/vite-plugin-windicss/dist/index.js:115:11)
    at reloadChangedCssModules (/web/node_modules/.pnpm/vite-plugin-windicss@1.7.0_vite@2.8.0/node_modules/vite-plugin-windicss/dist/index.js:144:44)
    at Timeout._onTimeout (/web/node_modules/.pnpm/vite-plugin-windicss@1.7.0_vite@2.8.0/node_modules/vite-plugin-windicss/dist/index.js:334:7)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
```

**Comment by sctgraham** [comment]
Got the same bug here too and have not been able to find a work around. Do you have an ETA for the PR merge ?

**Comment by sctgraham** [comment]
Works great, thanks !
