### ISSUE TITLE
Error with SvelteKit

### ISSUE THREAD

**Issue by NoelJacob** [windicss/vite-plugin-windicss#90]
**Describe the bug**

On Windows:
1) Did `pnpm init svelte@next`
2) Followed the steps in this repo with `import "virtual:windi.css"` inside `src/$layout.svelte`
3) `pnpm run dev` gives the error

**Minimal Reproductions**

[repository](https://github.com/NoelJacob/windicss)

**Versions**
- vite-plugin-windicss: 0.8.3
- vite: 2.1.0
- framework(vue/react/svelte/etc): sveltejs/kit 1.0.0-next.49

**Additonal Context**
On `pnpm run dev`: 
```
> Executing task: pnpm run dev <


> windinew@0.0.1 dev C:\Users\HP\Desktop\windinew
> svelte-kit dev

failed to load config from C:\Users\HP\Desktop\windinew\vite.config.js
> WindiCSS is not a function
TypeError: WindiCSS is not a function
    at file:///C:/Users/HP/Desktop/windinew/vite.config.js?t=1615900612482:14:3
    at ModuleJob.run (node:internal/modules/esm/module_job:154:23)
    at async Loader.import (node:internal/modules/esm/loader:166:24)
    at async loadConfigFromFile (C:\Users\HP\Desktop\windinew\node_modules\.pnpm\vite@2.1.0\node_modules\vite\dist\node\chunks\dep-6f1d3d8c.js:46129:31)
    at async resolveConfig (C:\Users\HP\Desktop\windinew\node_modules\.pnpm\vite@2.1.0\node_modules\vite\dist\node\chunks\dep-6f1d3d8c.js:45783:28)  
    at async Object.createServer (C:\Users\HP\Desktop\windinew\node_modules\.pnpm\vite@2.1.0\node_modules\vite\dist\node\chunks\dep-6f1d3d8c.js:68984:20)
    at async Watcher.init_server (file:///C:/Users/HP/Desktop/windinew/node_modules/.pnpm/@sveltejs/kit@1.0.0-next.49_d563d1e4217ff8882402c11be2b46d5a/node_modules/@sveltejs/kit/dist/chunks/index.js:3225:24)
    at async Watcher.init (file:///C:/Users/HP/Desktop/windinew/node_modules/.pnpm/@sveltejs/kit@1.0.0-next.49_d563d1e4217ff8882402c11be2b46d5a/node_modules/@sveltejs/kit/dist/chunks/index.js:3195:3)
    at async file:///C:/Users/HP/Desktop/windinew/node_modules/.pnpm/@sveltejs/kit@1.0.0-next.49_d563d1e4217ff8882402c11be2b46d5a/node_modules/@sveltejs/kit/dist/cli.js:474:20
file:///C:/Users/HP/Desktop/windinew/node_modules/.pnpm/@sveltejs/kit@1.0.0-next.49_d563d1e4217ff8882402c11be2b46d5a/node_modules/@sveltejs/kit/dist/chunks/index.js:3488
                this.viteDevServer.close();
                                   ^

TypeError: Cannot read property 'close' of undefined
    at Watcher.close (file:///C:/Users/HP/Desktop/windinew/node_modules/.pnpm/@sveltejs/kit@1.0.0-next.49_d563d1e4217ff8882402c11be2b46d5a/node_modules/@sveltejs/kit/dist/chunks/index.js:3488:22)
    at process.<anonymous> (file:///C:/Users/HP/Desktop/windinew/node_modules/.pnpm/@sveltejs/kit@1.0.0-next.49_d563d1e4217ff8882402c11be2b46d5a/node_modules/@sveltejs/kit/dist/chunks/index.js:3185:9)
    at process.emit (node:events:379:20)
    at process.EventEmitter.emit (node:domain:470:12)
    at process.exit (node:internal/process/per_thread:178:15)
    at handle_error (file:///C:/Users/HP/Desktop/windinew/node_modules/.pnpm/@sveltejs/kit@1.0.0-next.49_d563d1e4217ff8882402c11be2b46d5a/node_modules/@sveltejs/kit/dist/cli.js:451:10)
    at file:///C:/Users/HP/Desktop/windinew/node_modules/.pnpm/@sveltejs/kit@1.0.0-next.49_d563d1e4217ff8882402c11be2b46d5a/node_modules/@sveltejs/kit/dist/cli.js:487:4
 ERROR  Command failed with exit code 1.
```

**Comment by antfu** [comment]
Try

```ts
import { default as WindiCSS } from 'vite-plugin-windicss';
```

**Comment by NoelJacob** [comment]
> but if you remove the `type: "module"`, it works.

This works. Thank you.

> ```ts
> import { default as WindiCSS } from 'vite-plugin-windicss';
> ```

Could not get this to work.

Also could you tell if using svelte-windicss-preprocess or this one is better with SvelteKit?

**Comment by JustinVoitel** [comment]
@NoelJacob This worked for me without removing `type: "module"` :
```ts
import WindiCSS from 'vite-plugin-windicss'

export default {
  plugins: [WindiCSS.default()],
  // other kit stuff ...
}
```

**Comment by antfu** [comment]
Using `vite.config.ts` could be another option as well.

Close as this is more like a Node/ESM problem than the project itself. Thanks.

**Comment by ohmree** [comment]
I've also ran into this with `"type": "module"` (I load my vite config on the server and one of my server deps is esm-only so I have to use `"type": "module"` on both the client and the server).

A fix that seems to work perfectly is going into the plugin's `package.json` and adding this:
```json
"exports": {
  ".": {
    "import": "./dist/index.mjs",
    "require": "./dist/index.js"
  }
}
```
Which seems odd and redundant but hey, my editor doesn't complain anymore and it _seems_ to work fine in the vite dev server.
So is there a possibility of this fix getting added? Is there any drawback to adding it? Should I open a PR?

**Comment by joshua1** [comment]
@ohmree  you should do a PR for that. I added that to the package.json file and it fixed the import issue. I am keeping my version static with that change until this comes through . @antfu  accept PR please

**Comment by joaopaulobdac** [comment]
You need to import it like `import * as WindiCSS from "vite-plugin-windicss"` instead of `import WindiCSS from "vite-plugin-windicss"` otherwise you get this error:

```console
Error: Property 'default' does not exist on type '(userOptions?: UserOptions | undefined, utilsOptions?: WindiPluginUtilsOptions | undefined) => Plugin[]'. 
      },
      plugins: [WindiCSS.default()]
    }


====================================
svelte-check found 1 error, 0 warnings, and 0 hints
```

@ohmree @joshua1 @antfu What happened to the PR?

**Comment by ElMassimo** [comment]
Perhaps it would be reasonable to add a [similar fix to the one in `unplugin-icons`](https://github.com/antfu/unplugin-icons/blob/main/scripts/postbuild.ts#L17-L18) in this package?

It would be really cool if `tsup` supported this behavior out of the box, it would make it seamless to use Vite plugins in projects with or without `"type": "module"`.
